import os
Import('TopEnv')



curdir = Dir('.').srcnode().abspath


#incpath = '-I' + curdir+"/.."
#TopEnv.Append(CPPFLAGS=incpath)

TopEnv['LIBS'] += ['ssl']


curobj = TopEnv.Object(Glob('*.cpp')) + TopEnv.Object(Glob('*.cc'))

Return('curobj')
