/*
 * EdHttpHdr.h
 *
 *  Created on: Oct 3, 2014
 *      Author: netmind
 */

#ifndef EDHTTPHDR_H_
#define EDHTTPHDR_H_

enum {
	HDR__BEGIN,
	HDR_ACCEPT,
	HDR_ACCEPT_CHARSET,
	HDR_ACCEPT_ENCODING,
	HDR_ACCEPT_LANGUAGE,
	HDR_AGE,
	HDR_ALLOW,
	HDR_AUTHORIZATION,
	HDR_CACHE_CONTROL,
	HDR_CONNECTION,
	HDR_CONTENT_ENCODING,
	HDR_CONTENT_LANGUAGE,
	HDR_CONTENT_LENGTH,
	HDR_CONTENT_LOCATION,
	HDR_CONTENT_MD5,
	HDR_CONTENT_RANGE,
	HDR_CONENT_TYPE,
	HDR_DATE,
	HDR_ETAG,
	HDR_EXPECT,
	HDR_EXPIRES,
	HDR_FROM,
	HDR_HOST,
	HDR_IF_MATCH,
	HDR_IF_MODIFIED_SINCE,
	HDR_IF_NONE_MATH,
	HDR_IF_RANGE,
	HDR_IF_UNMODIFIED_SINCE,
	HDR_LAST_MODIFIED,
	HDR_LOCATION,
	HDR_MAX_FORWARDS,
	HDR_PRAGMA,
	HDR_PROXY_AUTHENTICATE,
	HDR_PROXY_AUTHORIZATION,
	HDR_RANGE,
	HDR_REFERER,
	HDR_RETRY_AFTER,
	HDR_SERVER,
	HDR_TE,
	HDR_TRAILER,
	HDR_TRANSFER_ENCODING,
	HDR_UPGRADE,
	HDR_USER_AGENT,
	HDR_VARY,
	HDR_VIA,
	HDR_WARNING,
	HDR_WWW_AUTHENTICATE,

	HDR__MAX,
};

#include "EdHdrContentDisposition.h"
#include "EdHdrContentType.h"
#include "EdHdrDate.h"

#endif /* EDHTTPHDR_H_ */
